from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('core','0002_novalm_and_login')]
 operations=[
 migrations.CreateModel(name='AIConversation',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(default='NovaHR conversation',max_length=200)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='ai_conversations',to='core.user'))],options={'ordering':['-updated_at']}),
 migrations.CreateModel(name='AIInsight',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('category',models.CharField(max_length=80)),('title',models.CharField(max_length=200)),('content',models.TextField()),('data',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True))]),
 migrations.CreateModel(name='AIMessage',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(max_length=20)),('content',models.TextField()),('metadata',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('conversation',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='messages',to='core.aiconversation'))],options={'ordering':['created_at']}),
 migrations.CreateModel(name='DocumentChunk',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('content',models.TextField()),('chunk_index',models.PositiveIntegerField()),('embedding',models.JSONField(blank=True,default=list)),('metadata',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('document',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='chunks',to='core.knowledgedocument'))]),
 migrations.CreateModel(name='AIQueryFeedback',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('rating',models.PositiveSmallIntegerField(default=3)),('feedback',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('message',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='feedback_items',to='core.aimessage'))]),
 migrations.AddConstraint(model_name='documentchunk',constraint=models.UniqueConstraint(fields=('document','chunk_index'),name='unique_document_chunk'))
 ]
